"""Central song system: session state, form ordering, database bridge."""

from .bpm_state import (
    BPM_WIDGET_KEY,
    request_backing_bpm,
    sync_backing_bpm_before_widget,
)
from .form import (
    chord_blocks_for_backing,
    form_timeline_rows,
    section_names_from_song,
    section_order,
)
from .key_state import (
    BACKING_NEEDS_REGEN,
    clear_backing_needs_regen,
    invalidate_backing_cache,
    note_display_key_change,
    on_cpl_jump_home_key,
    prepare_cpl_jump_home,
    request_display_key,
    sync_display_key_before_widget,
)
from .music_source import (
    ACTIVE_MUSIC_SOURCE_KEY,
    SOURCE_CATALOG,
    SOURCE_CUSTOM,
    active_source_banner,
    active_source_labels,
    unpack_active_source_banner,
    build_active_chart_bundle,
    display_key_context,
    ensure_active_music_source,
    is_custom_progression,
    note_active_source_change,
    set_catalog_source,
    set_custom_source,
    reconcile_picker_music_source,
    CATALOG_BEFORE_CUSTOM_KEY,
    commit_custom_active_song,
    custom_pick_key_for,
    custom_selected_song_record,
    queue_custom_active_song_activation,
    queue_custom_library_action,
    apply_pending_custom_active_song_activation_before_widgets,
    apply_pending_custom_library_action_before_widgets,
    PENDING_CUSTOM_ACTIVE_SONG_KEY,
    PENDING_CUSTOM_LIBRARY_ACTION_KEY,
)
from .picker_session import (
    CATALOG_FAVORITES_KEY,
    SONG_PICKER_FAVORITES_ONLY_KEY,
    SONG_SEARCH_RESET_REQUESTED_KEY,
    SONG_SEARCH_TEXT_KEY,
    WORKSPACE_GENRE_FILTERS_KEY,
    apply_picker_session_resets,
    prune_catalog_pick_keys,
    request_clear_browse_filters,
    toggle_catalog_favorite,
    toggle_favorites_filter,
    toggle_genre_filter,
)
from .state import (
    ACTIVE_CATALOG_PICK_KEY,
    PENDING_MATCHING_SONG_DROPDOWN,
    PICK_KEY_RECOVERY_NOTICE_KEY,
    SELECTED_SONG_STATE_KEY,
    apply_pick_key,
    build_music_local_state,
    ensure_master_song_initialized,
    get_song_context,
    persist_music_local_state,
    restore_saved_app_state_once,
    sync_matching_song_dropdown_before_widget,
)

__all__ = [
    # Catalog pick / master song (songs/state.py)
    "ACTIVE_CATALOG_PICK_KEY",
    "PENDING_MATCHING_SONG_DROPDOWN",
    "PICK_KEY_RECOVERY_NOTICE_KEY",
    "SELECTED_SONG_STATE_KEY",
    "apply_pick_key",
    "build_music_local_state",
    "ensure_master_song_initialized",
    "get_song_context",
    "persist_music_local_state",
    "restore_saved_app_state_once",
    "sync_matching_song_dropdown_before_widget",
    # Picker filters (songs/picker_session.py)
    "WORKSPACE_GENRE_FILTERS_KEY",
    "CATALOG_FAVORITES_KEY",
    "SONG_PICKER_FAVORITES_ONLY_KEY",
    "SONG_SEARCH_RESET_REQUESTED_KEY",
    "SONG_SEARCH_TEXT_KEY",
    "apply_picker_session_resets",
    "prune_catalog_pick_keys",
    "request_clear_browse_filters",
    "toggle_catalog_favorite",
    "toggle_favorites_filter",
    "toggle_genre_filter",
    # Music source
    "ACTIVE_MUSIC_SOURCE_KEY",
    "SOURCE_CATALOG",
    "SOURCE_CUSTOM",
    "active_source_banner",
    "active_source_labels",
    "unpack_active_source_banner",
    "build_active_chart_bundle",
    "display_key_context",
    "ensure_active_music_source",
    "is_custom_progression",
    "note_active_source_change",
    "set_catalog_source",
    "set_custom_source",
    "reconcile_picker_music_source",
    "CATALOG_BEFORE_CUSTOM_KEY",
    "commit_custom_active_song",
    "custom_pick_key_for",
    "custom_selected_song_record",
    "queue_custom_active_song_activation",
    "queue_custom_library_action",
    "apply_pending_custom_active_song_activation_before_widgets",
    "apply_pending_custom_library_action_before_widgets",
    "PENDING_CUSTOM_ACTIVE_SONG_KEY",
    "PENDING_CUSTOM_LIBRARY_ACTION_KEY",
    # Form / timeline
    "chord_blocks_for_backing",
    "form_timeline_rows",
    "section_order",
    "section_names_from_song",
    # BPM
    "BPM_WIDGET_KEY",
    "request_backing_bpm",
    "sync_backing_bpm_before_widget",
    # Display key / backing cache
    "BACKING_NEEDS_REGEN",
    "clear_backing_needs_regen",
    "invalidate_backing_cache",
    "note_display_key_change",
    "on_cpl_jump_home_key",
    "prepare_cpl_jump_home",
    "request_display_key",
    "sync_display_key_before_widget",
]
